title: Samuel Idaewor
logo: /assets/img/Edit.jpg
description: I am building expertise in data science based on my Software Engineering experience.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
